module.exports = {
  content: [
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {"synthwavey": {
        "primary": "#e779c1",
        "primary-focus": "#e04dac",
        "primary-content": "#201047",
        "secondary-focus": "#88d7f7",
        "secondary": "#58c7f3",
        "secondary-content": "#201047",
        "accent-focus": "#f6d860",
        "accent": "#f3cc30",
        "accent-content": "#201047",
        "neutral": "#20134e",
        "neutral-focus": "#140a2e",
        "neutral-content": "#f9f7fd",
        "base-100": "#181818",
        "base-200": "#282828",
        "base-300": "#404040",
        "base-content": "#f9f7fd",
        "info": "#53c0f3",
        "success": "#71ead2",
        "warning": "#f3cc30",
        "error": "#e24056",
        "--border-color": "var(--b3)",
        "--rounded-box": "1rem",
        "--rounded-btn": "0.5rem",
        "--rounded-badge": "1.9rem",
        "--animation-btn": "0.25s",
        "--animation-input": ".2s",
        "--btn-text-case": "uppercase",
        "--btn-focus-scale": "0.95",
        "--navbar-padding": ".5rem",
        "--border-btn": "1px",
        "--tab-border": "1px",
        "--tab-radius": "0.5rem",
      }},
    ],
  },  
}
